name: k8s Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy_shortener:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: azure/setup-kubectl@v1
        with:
          version: 'v1.18.8'
        id: install
      
      - name: Setup kubeconfig
        env:
          KUBECONFIG_CONTENTS: ${{ secrets.KUBECONFIG }}
        run: echo "$KUBECONFIG_CONTENTS" > $HOME/kubeconfig && echo "::set-env name=KUBECONFIG::$HOME/kubeconfig"

      - name: Install envsubst
        run: sudo apt install -y gettext-base

      - name: Deploy secrets
        env:
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          OAUTH_PROXY_SECRET: ${{ secrets.OAUTH_PROXY_SECRET }}
        run: cat k8s/secrets.yml | envsubst | kubectl apply -f -

      - name: Deploy App
        run: kubectl apply -f k8s/oauth2-proxy.yml -f k8s/app.yml -f k8s/ingress.yml
